### PR TITLE
fix format amount

### LINKED ISSUE #5162: Format alternative amount - Confirm view
Alternative amount is not correctly formated

* USD

copay_-_copay_bitcoin_wallet

copay_-_copay_bitcoin_wallet

* EUR

copay_-_copay_bitcoin_wallet

copay_-_copay_bitcoin_wallet

### PR DESCRIPTION
**Pull request by JDonadio**
Fixes #5162

### CODE REVIEW

**Comment by JDonadio** [comment]
Good catch @cmgustavo. Updated now.

File: src/js/services/txFormatService.js [hunk 1]
```diff
@@ -48,10 +48,11 @@ angular.module('copayApp.services').factory('txFormatService', function(bwcServi
     var config = configService.getSync().wallet.settings;
 
     var val = function() {
-      var v1 = rateService.toFiat(satoshis, config.alternativeIsoCode);
+      var v1 = parseFloat((rateService.toFiat(satoshis, config.alternativeIsoCode)).toFixed(2), 10);
```
Comment (cmgustavo) [inline src/js/services/txFormatService.js]: What does the number `10` means?

Comment (JDonadio) [inline src/js/services/txFormatService.js]: This is an error, that parameters does nothing. 👍
