### PR TITLE
Fixes modal of transaction proposals

### LINKED ISSUE #4975: Transaction proposal should update the timeline when copayers accepts/rejects it

### PR DESCRIPTION
**Pull request by cmgustavo**
fixes #4975

* Fix error if backView does not exist when joining to a wallet
* Updates information (timeline) when copayers accept/reject a transaction
* Adds alert before delete transaction
* Fix delete transaction

### CODE REVIEW

File: src/js/controllers/modals/txpDetails.js [hunk 1]
```diff
@@ -1,13 +1,11 @@
...
-angular.module('copayApp.controllers').controller('txpDetailsController', function($scope, $rootScope, $timeout, $interval, $ionicModal, $log, ongoingProcess, platformInfo, $ionicScrollDelegate, txFormatService, fingerprintService, bwcError, gettextCatalog, lodash, walletService, popupService, $state, $ionicHistory) {
-  var self = $scope.self;
-  var tx = $scope.tx;
-  var copayers = $scope.copayers;
+angular.module('copayApp.controllers').controller('txpDetailsController', function($scope, $rootScope, $timeout, $interval, $log, ongoingProcess, platformInfo, $ionicScrollDelegate, txFormatService, bwcError, gettextCatalog, lodash, walletService, popupService, $ionicHistory) {
   var isGlidera = $scope.isGlidera;
   var GLIDERA_LOCK_TIME = 6 * 60 * 60;
   var now = Math.floor(Date.now() / 1000);
   var countDown;
+  var listeners = [];
```
Comment (JDonadio) [inline src/js/controllers/modals/txpDetails.js]: Not used?

Comment (cmgustavo) [inline src/js/controllers/modals/txpDetails.js]: Yes, you are right. Thanks!

**Comment by gabrielbazan7** [comment]
ACK
