### PR TITLE
Fix tx-detail

### LINKED ISSUE #4983: Tx details does not update info (cached)

### PR DESCRIPTION
**Pull request by cmgustavo**
* Updates tx-detail (cached)
* Fix search: open tx

fixes #4983

### CODE REVIEW

File: src/js/controllers/tx-details.js [hunk 1]
```diff
@@ -109,27 +92,21 @@ angular.module('copayApp.controllers').controller('txDetailsController', functio
     }
     if ($scope.btx.note && $scope.btx.note.body) opts.defaultText = $scope.btx.note.body;
 
-    popupService.showPrompt(wallet.name, gettextCatalog.getString('Memo'), opts, function(text) {
+    popupService.showPrompt($scope.wallet.name, gettextCatalog.getString('Memo'), opts, function(text) {
       if (typeof text == "undefined") return;
 
+      $scope.btx.note.body = text;
```
Comment (JDonadio) [inline src/js/controllers/tx-details.js]: Transactions without notes will crash in this line, should be defined as:

>var note = {
        body: text
      };
      $scope.btx.note = note;

**Comment by JDonadio** [comment]
LGTM

**Comment by gabrielbazan7** [comment]
ACK
